CREATE DATABASE IF NOT EXISTS beadando;

USE beadando;

CREATE TABLE IF NOT EXISTS Films (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Director VARCHAR(255) NOT NULL,
    ReleaseYear INT NOT NULL
);
